### ISSUE TITLE
Preprocessor Incomplete

### ISSUE THREAD

**Issue by neomannskar** [Totem-Studios/lotus#16]
To force a new and more elegant standard it is debatable whether to support preprocessor directives like the header guards:
- if
- ifdef
- ifndef

However, sticking to one of Lotus's goals of it being multi-paradigm it will be implemented. It is not yet complete however.

**Comment by pontushenriksson** [comment]
This issue is extensive and requires much effort. If this issue is still relevant then split it into multiple smaller issues. If the issues are smaller they can also easier be linked with different pull requests.
