### ISSUE TITLE
General Diagnostics Not Implemented

### ISSUE THREAD

**Issue by neomannskar** [Totem-Studios/lotus#18]
Currently the Lotus compiler offers minimal debugging support. There are a few simple functions created that are incomplete and nonstandard.

**Comment by pontushenriksson** [comment]
This issue should be closed and be replaced with more issues about specific bit-sized features that should be implemented.

**Comment by pontushenriksson** [comment]
Please refer to [Issue 24](https://github.com/Totem-Studios/lotus/issues/24) for more information. This is now closed.
